version: '3.6'

services:
  dns:
    container_name: dns
    domainname: docker
    hostname: dns
    image: mcarson75/unbound-pihole:amd64
    networks:
      lan:
        ipv4_address: $LOCAL_IP
    restart: unless-stopped
# Uncomment ports section if not using external network
#    ports:
#      - '53:53/tcp'
#      - '53:53/udp'
#      - '80:80'
#      - '443:443'
#      - '5053:5053/tcp'
#      - '5053:5053/udp'
    volumes:
      - /etc/dns/pihole:/etc/pihole
      - /etc/dns/dnsmasq.d:/etc/dnsmasq.d
      - /etc/dns/unbound:/opt/unbound/etc/unbound
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: $LOCAL_IP
      TZ: 'America/New_York'
      WEBPASSWORD: ''
      DNS1: 127.0.0.1#5053
      DNS2: "no"
      IPV6: "no"

networks:
  lan:
    external: true
